#!/bin/sh

# Wait for the property system to be up.
while [ ! -e /dev/socket/property_service ]; do sleep 0.5; done

# Wait for properties to be loaded.
while [ "$(getprop init.svc.vendor.wifi_hal_legacy)" != "running" ]; do sleep 0.5; done

# Initialize qcacld wlan module via writing ON to /dev/wlan
while [ ! -e /dev/wlan ]; do sleep 1; done
echo ON > /dev/wlan

# Enable WoWLAN to stay connected during suspend
while [ ! -e /sys/class/ieee80211/phy0 ]; do sleep 1; done
iw phy phy0 wowlan enable any
